### PR TITLE
Handle anonymous parameters, not just named parameters

### LINKED ISSUE #7: if any position parameters are supplied, then params throws an exception
This should at the very last not throw an exception if there is a position rather than named parameter present, e.g. like:

    {{Foo|blah}}

... rather than `{{Foo|baz=blah}}`

### PR DESCRIPTION
**Pull request by mhl**
Previously if you included an anonymous parameter, e.g. had a template
tag like:

    {{MyAwesomeTemplate|1234}}

... you would just get an exception. This is also common for people to
do when they don't understand that the template is expecting a named
parameter.

This pull request stops that happening, and makes "anonymous parameters" like
these available as and array under the `.anonymous_params` of a section.

It also handles numbered parameters, making their integer value the key in
`.params`.

Fixes #7

### CODE REVIEW

File: lib/mediawiki/page.rb [hunk 1]
```diff
@@ -24,16 +26,33 @@ def replace_output(new_content, run_comment = '')
...
-        end.to_h
+          m = NAMED_TEMPLATE_PARAM_RE.match(p)
+          param_key_value_array(*m.captures) if m
+        end.compact.to_h
+      end
+
+      def anonymous_params
+        # FIXME: untemplate these using the MediaWiki API before
+        # returning them.
+        all_parameters.map { |p| NAMED_TEMPLATE_PARAM_RE =~ p ? nil : p }.compact
```
Comment (tmtmtmtm) [inline lib/mediawiki/page.rb:55]: I think this would simpler and clearer as:

```ruby
all_parameters.select { |p| NAMED_TEMPLATE_PARAM_RE =~ p }
```

File: lib/mediawiki/page.rb [hunk 2]
```diff
@@ -24,16 +26,33 @@ def replace_output(new_content, run_comment = '')
         client.edit(title: title, text: new_wikitext)
       end
 
+      def param_key_value_array(key, value)
```
Comment (tmtmtmtm) [inline lib/mediawiki/page.rb:29]: Is this meant to be part of the public interface? If it's only expected to be called from within `params`, it's probably better to make it private.
